
const data =   [
  {
      "children": [
          {
              "children": [
                  {
                      "update_time": null,
                      "create_time": null,
                      "listorder": 80,
                      "condition": "",
                      "status": "1",
                      "hidden": 0,
                      "redirect": "",
                      "icon": "",
                      "title": "信息列表",
                      "type": 2,
                      "component": "",
                      "path": "/sys/menu/info",
                      "name": "JbTm_sys_menu_view",
                      "pid": 2,
                      "id": 9,
                      "perm_id": "10"
                  },
                  {
                      "update_time": null,
                      "create_time": null,
                      "listorder": 90,
                      "condition": "",
                      "status": "1",
                      "hidden": 0,
                      "redirect": "",
                      "icon": "",
                      "title": "添加",
                      "type": 2,
                      "component": "",
                      "path": "/sys/menu/add",
                      "name": "TbtV_sys_menu_add",
                      "pid": 2,
                      "id": 6,
                      "perm_id": "7"
                  },
                  {
                      "update_time": null,
                      "create_time": null,
                      "listorder": 95,
                      "condition": "",
                      "status": "1",
                      "hidden": 0,
                      "redirect": "",
                      "icon": "",
                      "title": "编辑",
                      "type": 2,
                      "component": "",
                      "path": "/sys/menu/edit",
                      "name": "SJvm_sys_menu_edit",
                      "pid": 2,
                      "id": 7,
                      "perm_id": "8"
                  },
                  {
                      "update_time": null,
                      "create_time": null,
                      "listorder": 99,
                      "condition": "",
                      "status": "1",
                      "hidden": 0,
                      "redirect": "",
                      "icon": "",
                      "title": "删除",
                      "type": 2,
                      "component": "",
                      "path": "/sys/menu/del",
                      "name": "tTub_sys_menu_del",
                      "pid": 2,
                      "id": 8,
                      "perm_id": "9"
                  }
              ],
              "update_time": null,
              "create_time": null,
              "listorder": 80,
              "condition": "",
              "status": "1",
              "hidden": 0,
              "redirect": "",
              "icon": "menu1",
              "title": "菜单管理",
              "type": 1,
              "component": "sys/menu/index",
              "path": "/sys/menu",
              "name": "snIc_sys_menu",
              "pid": 1,
              "id": 2,
              "perm_id": "3"
          },
          {
              "children": [
                  {
                      "update_time": null,
                      "create_time": null,
                      "listorder": 90,
                      "condition": "",
                      "status": "1",
                      "hidden": 0,
                      "redirect": "",
                      "icon": "",
                      "title": "信息列表",
                      "type": 2,
                      "component": "",
                      "path": "/sys/role/info",
                      "name": "tyli_sys_role_info",
                      "pid": 3,
                      "id": 13,
                      "perm_id": "14"
                  },
                  {
                      "update_time": null,
                      "create_time": null,
                      "listorder": 91,
                      "condition": "",
                      "status": "1",
                      "hidden": 0,
                      "redirect": "",
                      "icon": "",
                      "title": "添加",
                      "type": 2,
                      "component": "",
                      "path": "/sys/role/add",
                      "name": "AtyQ_sys_role_add",
                      "pid": 3,
                      "id": 14,
                      "perm_id": "15"
                  },
                  {
                      "update_time": null,
                      "create_time": null,
                      "listorder": 92,
                      "condition": "",
                      "status": "1",
                      "hidden": 0,
                      "redirect": "",
                      "icon": "",
                      "title": "编辑",
                      "type": 2,
                      "component": "",
                      "path": "/sys/role/edit",
                      "name": "rEzJ_sys_role_edit",
                      "pid": 3,
                      "id": 15,
                      "perm_id": "16"
                  },
                  {
                      "update_time": null,
                      "create_time": null,
                      "listorder": 101,
                      "condition": "",
                      "status": "1",
                      "hidden": 0,
                      "redirect": "",
                      "icon": "",
                      "title": "删除",
                      "type": 2,
                      "component": "",
                      "path": "/sys/role/del",
                      "name": "evYv_sys_role_del",
                      "pid": 3,
                      "id": 16,
                      "perm_id": "17"
                  }
              ],
              "update_time": null,
              "create_time": null,
              "listorder": 99,
              "condition": "",
              "status": "1",
              "hidden": 0,
              "redirect": "",
              "icon": "people",
              "title": "角色管理",
              "type": 1,
              "component": "sys/role/index",
              "path": "/sys/role",
              "name": "CkoF_sys_role",
              "pid": 1,
              "id": 3,
              "perm_id": "4"
          },
          {
              "update_time": null,
              "create_time": null,
              "listorder": 99,
              "condition": "",
              "status": "1",
              "hidden": 0,
              "redirect": "",
              "icon": "user",
              "title": "用户管理",
              "type": 1,
              "component": "pdf/index",
              "path": "/sys/user",
              "name": "PhjC_sys_user",
              "pid": 1,
              "id": 4,
              "perm_id": "5"
          },
          {
              "update_time": null,
              "create_time": null,
              "listorder": 100,
              "condition": "",
              "status": "1",
              "hidden": 0,
              "redirect": "",
              "icon": "icon",
              "title": "图标管理",
              "type": 1,
              "component": "svg-icons/index",
              "path": "/sys/icon",
              "name": "QJYW_sys_icon",
              "pid": 1,
              "id": 12,
              "perm_id": "13"
          }
      ],
      "update_time": null,
      "create_time": null,
      "listorder": 99,
      "condition": "",
      "status": "1",
      "hidden": 0,
      "redirect": "/sys/menu",
      "icon": "sysset2",
      "title": "系统管理",
      "type": 0,
      "component": "Layout",
      "path": "/sys",
      "name": "DHDv_sys",
      "pid": 0,
      "id": 1,
      "perm_id": "2"
  },
  {
      "children": [
          {
              "update_time": null,
              "create_time": null,
              "listorder": 95,
              "condition": "",
              "status": "1",
              "hidden": 0,
              "redirect": "",
              "icon": "form",
              "title": "vue课堂测试",
              "type": 1,
              "component": "xiangjun/index",
              "path": "/sysx/xiangjun",
              "name": "AleS_sysx_xiangjun",
              "pid": 5,
              "id": 10,
              "perm_id": "11",
              "children": []
          },
          {
              "update_time": null,
              "create_time": null,
              "listorder": 99,
              "condition": "",
              "status": "1",
              "hidden": 0,
              "redirect": "",
              "icon": "form",
              "title": "上传证件照",
              "type": 1,
              "component": "uploadimg/index",
              "path": "/sysx/uploadimg",
              "name": "rAfb_sysx_uploadimg",
              "pid": 5,
              "id": 11,
              "perm_id": "12",
              "children": []
          }
      ],
      "update_time": null,
      "create_time": null,
      "listorder": 100,
      "condition": "",
      "status": "1",
      "hidden": 0,
      "redirect": "/sysx/xiangjun",
      "icon": "plane",
      "title": "测试菜单",
      "type": 0,
      "component": "Layout",
      "path": "/sysx",
      "name": "fGoY_sysx",
      "pid": 0,
      "id": 5,
      "perm_id": "6"
  }
]
export default data

